version: "3.1"
services:
  postgres:
    image: postgres:14
    container_name: pg_container
    restart: always
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bancogazin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      #PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/data/postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

  app:
    build: .
    container_name: api_container
    working_dir: /api
    environment:
      - NODE_ENV=production
      - PRISMA_HOST=prisma
    ports:
      - 5000:5000
    links:
      - postgres
    depends_on:
      - postgres
    #command: npm install && ./node_modules/.bin/prisma deploy && npm start

volumes:
  pgdata:
    driver: local




